name: Deploy Spring Boot App to EC2 via DockerHub

on:
  push:
    branches: [main]  # main 브랜치에 push가 발생할 때 트리거됨
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub Actions에서 사용할 runner 환경
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 현재 GitHub 레포의 코드 가져오기

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # OpenJDK 기반 배포판 사용

      - name: Build Spring Boot App
        run: ./gradlew clean bootJar  # JAR 파일 빌드

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub ID
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # DockerHub Access Token

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/customs-chatbot:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/customs-chatbot:latest

      - name: Deploy on EC2 via SSM
        uses: aws-actions/aws-ssm-run-command@v1
        with:
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          region: ap-northeast-2
          comment: "Deploy customs-chatbot"
          parameters: |
            commands=cd ~/CustomsChatBotBE &&
            git pull origin main &&
            chmod +x deploy.sh &&
            ./deploy.sh